
#ifndef _MRD_SPECS_
#define _MRD_SPECS_ 1
Double_t mrdzstart=1990;
Double_t mrdzlen=919;
Int_t mrdnumlayers=12;		  // 12 layers of scintillator, steel. 13 alu structs, but they're not really important. 
Int_t mrdpaddlesperpanel=30;	  // remember TWO ROWS of 15 paddles!!

Double_t steelfullxlen = 274;
Double_t steelfullylen = 305;
Double_t steelfullzlen = 5;

Double_t scintfullxlen = 20;
Double_t scintfullzlen= 0.6;
Double_t scintvfullylen = 155;
Double_t scinthfullylen= 138;

Double_t scinttapfullwidth = 17.1; 			
Double_t scinttapfullheight = 7.8; 			

Double_t scintlgfullwidth = 10.16; 			
Double_t scintlgfullheight = 16.67; 			

Double_t alufullxlen = steelfullxlen+5;	
Double_t alufullylen = steelfullylen+5;	
Double_t alufullzlen = 1.9;							
Double_t alufullxthickness = 2.54;				
Double_t alufullythickness = 2.54;
Double_t windowwidth = (steelfullxlen-(4*alufullxthickness))/3;	
Double_t windowheight= (steelfullylen-(4*alufullythickness))/3;

Double_t scintzedges[24] = {19, 25, 75, 81, 150, 156, 225, 231, 300, 306, 375, 381, 450, 456, 525, 531, 600, 606, 675, 681, 750, 756, 825, 831};// taken from printed output generated by SteppingAction.cc at line 122

#endif 
