/********************************************************************
* ./src/WCLRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./src/WCLRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWCLRootDict();
extern void G__cpp_setup_inheritanceWCLRootDict();
extern void G__cpp_setup_typetableWCLRootDict();
extern void G__cpp_setup_memvarWCLRootDict();
extern void G__cpp_setup_globalWCLRootDict();
extern void G__cpp_setup_memfuncWCLRootDict();
extern void G__cpp_setup_funcWCLRootDict();
extern void G__set_cpp_environmentWCLRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "WCSimRecoObjectTable.hh"
#include "WCSimRecoDigit.hh"
#include "WCSimRecoCluster.hh"
#include "SandBoxPMTcoverage.hh"
#include "WCSimTrueLight.hh"
#include "WCSimTruePart.hh"
#include "WCSimTrueCapture.hh"
#include "WCSimTrueLightCluster.hh"
#include "WCLTreeReader.hh"
#include "WCLTreeWriter.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WCLRootDictLN_TClass;
extern G__linked_taginfo G__WCLRootDictLN_TBuffer;
extern G__linked_taginfo G__WCLRootDictLN_TMemberInspector;
extern G__linked_taginfo G__WCLRootDictLN_TObject;
extern G__linked_taginfo G__WCLRootDictLN_TString;
extern G__linked_taginfo G__WCLRootDictLN_basic_fstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCLRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCLRootDictLN_WCSimRecoObjectTable;
extern G__linked_taginfo G__WCLRootDictLN_WCSimRecoDigit;
extern G__linked_taginfo G__WCLRootDictLN_WCSimRecoCluster;
extern G__linked_taginfo G__WCLRootDictLN_vectorlEWCSimRecoDigitmUcOallocatorlEWCSimRecoDigitmUgRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_reverse_iteratorlEvectorlEWCSimRecoDigitmUcOallocatorlEWCSimRecoDigitmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCLRootDictLN_SandBoxPMTcoverage;
extern G__linked_taginfo G__WCLRootDictLN_WCSimTrueLight;
extern G__linked_taginfo G__WCLRootDictLN_WCSimTruePart;
extern G__linked_taginfo G__WCLRootDictLN_WCSimTrueCapture;
extern G__linked_taginfo G__WCLRootDictLN_WCSimTrueLightCluster;
extern G__linked_taginfo G__WCLRootDictLN_vectorlEWCSimTrueLightmUcOallocatorlEWCSimTrueLightmUgRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_reverse_iteratorlEvectorlEWCSimTrueLightmUcOallocatorlEWCSimTrueLightmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCLRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__WCLRootDictLN_TTree;
extern G__linked_taginfo G__WCLRootDictLN_TFile;
extern G__linked_taginfo G__WCLRootDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_TChain;
extern G__linked_taginfo G__WCLRootDictLN_WCLTreeReader;
extern G__linked_taginfo G__WCLRootDictLN_WCLTreeWriter;

/* STUB derived class for protected member access */
